sudo: false
language: node_js
node_js:
- '0.10'
- '0.12'
- '4.0'
- '5.0'
env:
  global:
    secure: HhkC5gey2MPv/2tEjudZAlMa6jLkp9f02vgBjLw/vfcuE+bz9NC1LwlUTw6whyoIH9lfUBTBaYxz9v7Vj5A+oDP5rVF5l5boy33Ly4HS2p806fcFxPLfbf5x1zq9yu0QKq6Cn9DhX5iLSIWJpIxjjWIzdFF8C6cGxdUvOLoOFi4=
